### PR TITLE
Upgrade to symfony 6.3

### PR DESCRIPTION
**Pull request by hbagherzadegan**
### please **don't merge** this untill all service ready for symfony 6.3

### CODE REVIEW

**Comment by JarJak** [comment]
Would be good to update with https://github.com/FriendsOfBehat/SymfonyExtension.
Actually I don't think we need this repo at all. The only commit done in our fork is https://github.com/FriendsOfBehat/SymfonyExtension/compare/master...kollex:SymfonyExtension:master

**Comment by hbagherzadegan** [comment]
> Would be good to update with https://github.com/FriendsOfBehat/SymfonyExtension. Actually I don't think we need this repo at all. The only commit done in our fork is [FriendsOfBehat/SymfonyExtension@master...kollex:SymfonyExtension:master](https://github.com/FriendsOfBehat/SymfonyExtension/compare/master...kollex:SymfonyExtension:master)

yep , but i guess it's may take time to accepted , any how we could have both , so basically we could merged it to our repo and then create another pr against SymfonyExtention later

**Comment by JarJak** [comment]
I mean we don't need this repo at all, because the original one is Symfony 6.x ready

**Comment by hbagherzadegan** [comment]
> I mean we don't need this repo at all, because the original one is Symfony 6.x ready

i checked that one is on symfony 6.1 that's why i update our repo to symfony 6.3

**Comment by JarJak** [comment]
> > I mean we don't need this repo at all, because the original one is Symfony 6.x ready
> 
> i checked that one is on symfony 6.1 that's why i update our repo to symfony 6.3

I can see it requires `^6.0` so 6.3 will work: https://github.com/FriendsOfBehat/SymfonyExtension/blob/master/composer.json

**Comment by hbagherzadegan** [comment]
> > > I mean we don't need this repo at all, because the original one is Symfony 6.x ready
> > 
> > 
> > i checked that one is on symfony 6.1 that's why i update our repo to symfony 6.3
> 
> I can see it requires `^6.0` so 6.3 will work: https://github.com/FriendsOfBehat/SymfonyExtension/blob/master/composer.json

well i think there was some issue with 6.3 and it just solved for 6.1 , any how as team make a choice if we wanna archive this repos from my opinion one repo less for maintenance @JarJak , why not ;)

**Comment by JarJak** [comment]
> > > > I mean we don't need this repo at all, because the original one is Symfony 6.x ready
> > > 
> > > 
> > > i checked that one is on symfony 6.1 that's why i update our repo to symfony 6.3
> > 
> > 
> > I can see it requires `^6.0` so 6.3 will work: [FriendsOfBehat/SymfonyExtension@`master`/composer.json](https://github.com/FriendsOfBehat/SymfonyExtension/blob/master/composer.json?rgh-link-date=2023-07-28T11%3A13%3A05Z)
> 
> well i think there was some issue with 6.3 and it just solved for 6.1 , any how as team make a choice if we wanna archive this repos from my opinion one repo less for maintenance @JarJak , why not ;)

let's ask @leopcastro for opinion

**Comment by hbagherzadegan** [comment]
> > > > > I mean we don't need this repo at all, because the original one is Symfony 6.x ready
> > > > 
> > > > 
> > > > i checked that one is on symfony 6.1 that's why i update our repo to symfony 6.3
> > > 
> > > 
> > > I can see it requires `^6.0` so 6.3 will work: [FriendsOfBehat/SymfonyExtension@`master`/composer.json](https://github.com/FriendsOfBehat/SymfonyExtension/blob/master/composer.json?rgh-link-date=2023-07-28T11%3A13%3A05Z)
> > 
> > 
> > well i think there was some issue with 6.3 and it just solved for 6.1 , any how as team make a choice if we wanna archive this repos from my opinion one repo less for maintenance @JarJak , why not ;)
> 
> let's ask @leopcastro for opinion

yep I agree , i think i just solve some psalm problem there , so at least we could give it a try and if it's not passed then we have this , @leopcastro  i'm agree with @JarJak , so it's good to give a try to real SymfonyExtension and if it's work then archived this repo , what's your idea

**Comment by leopcastro** [comment]
I also agree to try to remove this repo use the official one instead 👍

**Pull request closed without merging**
